# make it so that diagnostics displays clippy hints and not just warnings and errors
[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true

# for typst
[language-server.tinymist]
command = "tinymist"

[[language]]
name = "typst"
language-servers = ["tinymist"]
       
[[language]]
name = "markdown"
language-servers = ["markdown-oxide"]
